"""revrse quantity

Revision ID: 24a40fea84e4
Revises: 3a6c9a080ab2
Create Date: 2025-04-23 16:55:35.519482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a40fea84e4'
down_revision: Union[str, None] = '3a6c9a080ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet_products', sa.Column('quantity', sa.Float(), nullable=True))
    op.drop_column('diets', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diets', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('diet_products', 'quantity')
    # ### end Alembic commands ###
