"""change products

Revision ID: 3a6c9a080ab2
Revises: d0a96895cd1c
Create Date: 2025-04-23 14:54:47.762958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6c9a080ab2'
down_revision: Union[str, None] = 'd0a96895cd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diet_products', 'quantity')
    op.add_column('diets', sa.Column('quantity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diets', 'quantity')
    op.add_column('diet_products', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
